name: Auto Update and Publish to PyPI
# This workflow is triggered on push to main branch and on a schedule every day at midnight. It also updates any dependencies and runs tests before publishing to PyPI.
# NOTE: the current workflow requires manual intervention in updating dependencies.
# ...If the dependencies are not changed, then the workflow will continue and publish to PyPI with same denendencies as defined.

on:
  push:
    branches:
      - main # Currently triggers on any push to main branch
  schedule:
    - cron: "0 0 * * *" # Added a scheduled trigger to run every day at midnight

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine pytest

      - name: Run tests with pytest
        run: |
          pytest test # running only core tests for now

      - name: Build binary wheel and a source tarball
        run: |
          python setup.py sdist bdist_wheel

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository-url: https://upload.pypi.org/legacy/
